# Dockerfile

FROM python:3.11-slim-bookworm AS builder

RUN apt-get update && \
    apt-get upgrade --yes

RUN useradd --create-home realbanana
USER realbanana
WORKDIR /home/realbanana

ENV VIRTUALENV=/home/realbanana/venv
RUN python3 -m venv $VIRTUALENV
ENV PATH="$VIRTUALENV/bin:$PATH"

# Default is `superuser`
COPY --chown=realbanana pyproject.toml constraints.txt ./

RUN python -m pip install --upgrade pip setuptools && \
    python -m pip install --no-cache-dir -c constraints.txt ".[dev]"

# ---
COPY --chown=realbanana src/ src/
COPY --chown=realbanana test/ test/

RUN python -m pip install . -c constraints.txt && \
    python -m pytest test/unit/ && \
    python -m flake8 src/ && \
    python -m isort src/ --check && \
    python -m black src/ --check --quiet && \
    python -m pylint src/ --disable=C0114,C0116,R1705 && \
    python -m bandit -r src/ --quiet && \
    python -m pip wheel --wheel-dir dist/ . -c constraints.txt

